# Лабораторная работа №3. NumPy

## Задание

Выполните следующие задания:

1. Откройте в файл в Google Colab (используйте собственный форк репозитория).
2. Решите задачи.
3. Сохраните результат в ваш репозиторий github в директорию ./les03
4. Создайте pull request в репозиторий https://github.com/chebotarevsa/dap-2024. Название pull request должно иметь формат "<Номер лабораторной работы>  <Номер группы> <ФИО>"
5. Сдайте работу в системе "Пегас", в отчет укажите ссылку на pull request

In [ ]:
import numpy as np
np.version.version

'2.1.0'

1. Создать массив 10x10 со случайными значениями, найти минимум и максимум (низкая)

In [1]:
import numpy as np
array = np.random.randint(0, 101, size=(10, 10))
min_value = np.min(array)
max_value = np.max(array)
print("Массив:")
print(array)
print(f"Минимум: {min_value}")
print(f"Максимум: {max_value}")

Массив:
[[44 32 91 15 64  1 28 95 97 27]
 [95 96 27 26 53 62 23 65 69 66]
 [93 15 37 55 65 39 26 70 36 51]
 [ 1 53 98  9 17 45 88 54  9 45]
 [21 58 90 75 97 27 21  1 36  4]
 [46 49 16 74 31 69 83  4  1 14]
 [ 8  1  6 92 35 25 65 62 13  3]
 [76 71 45 43 67 32 61 23 77 80]
 [31 21 35 77 98 77 87 41 50 11]
 [97  0 84 89  6 64 59 15 39 29]]
Минимум: 0
Максимум: 98


2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке

In [2]:
import numpy as np
matrix = np.zeros((8, 8), dtype=int)
for i in range(8):
    for j in range(8):
        if (i + j) % 2 == 0:
            matrix[i, j] = 1
print("8x8 матрица в шахматном порядке:")
print(matrix)

8x8 матрица в шахматном порядке:
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8

In [3]:
import numpy as np
array = np.random.randint(-10, 11, size=11)
print("Исходный массив:")
print(array)
for i in range(len(array)):
    if 3 <= array[i] <= 8:
        array[i] = -array[i]
print("Массив после изменения знака:")
print(array)

Исходный массив:
[ -8  -1   0   1  -3   4  10   0 -10   0  -7]
Массив после изменения знака:
[ -8  -1   0   1  -3  -4  10   0 -10   0  -7]


4. Найти среднее заначение строки матрицы и вычесть его из каждого елемента строки

In [4]:
import numpy as np
z = np.random.rand(5, 10)
row_means = np.mean(z, axis=1, keepdims=True)
centered_z = z - row_means
print("Исходная матрица z:")
print(z)
print("\nСредние значения строк:")
print(row_means.flatten())
print("\nМатрица после вычитания средних из элементов строк:")
print(centered_z)

Исходная матрица z:
[[0.11891919 0.05964314 0.58289684 0.90423985 0.04676892 0.36161145
  0.80751538 0.67672244 0.54641177 0.64392541]
 [0.07045386 0.01278765 0.94965485 0.70773956 0.68718824 0.2317736
  0.0908888  0.11214049 0.89688283 0.2299308 ]
 [0.4923715  0.33069987 0.4602982  0.06986997 0.99718173 0.89068439
  0.60907979 0.95029125 0.43618413 0.62040091]
 [0.37401022 0.82411184 0.89934354 0.94484718 0.33209249 0.63140309
  0.32950849 0.63658354 0.92058224 0.71093029]
 [0.03357102 0.34530733 0.48226541 0.34146754 0.9998582  0.85654351
  0.45680953 0.46560981 0.98985962 0.72785303]]

Средние значения строк:
[0.47486544 0.39894407 0.58570617 0.66034129 0.5699145 ]

Матрица после вычитания средних из элементов строк:
[[-0.35594625 -0.4152223   0.1080314   0.42937441 -0.42809652 -0.11325399
   0.33264994  0.20185701  0.07154633  0.16905997]
 [-0.32849021 -0.38615641  0.55071078  0.30879549  0.28824417 -0.16717047
  -0.30805527 -0.28680358  0.49793877 -0.16901327]
 [-0.09333468 -0.255

5. Поменяйте 1 и 2 строки матрицы

In [5]:
import numpy as np
z = np.arange(25).reshape(5, 5)
print("Исходная матрица z:")
print(z)
z[[0, 1]] = z[[1, 0]]
print("\nМатрица после замены 1-й и 2-й строк:")
print(z)

Исходная матрица z:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Матрица после замены 1-й и 2-й строк:
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


6. Дан массив 10x2 подеставлющий собой точки в декартовой системе координат, преобразовать в полярную

In [ ]:
import numpy as np
z = np.random.random((10, 2))
print("Исходный массив z (декартовы координаты x, y):")
print(z)
# Вычислить радиус r = sqrt(x^2 + y^2)
r = np.sqrt(z[:, 0]**2 + z[:, 1]**2)
# Вычислить угол theta = atan2(y, x) в радианах
theta = np.arctan2(z[:, 1], z[:, 0])
# Создать новый массив с полярными координатами (r, theta)
polar_z = np.column_stack((r, theta))
print("\nМассив в полярных координатах (r, theta в радианах):")
print(polar_z)

7. Заменить максимальный элемент массива на ноль

In [6]:
import numpy as np
z = np.random.random(10)
print("Исходный массив z:")
print(z)
max_index = np.argmax(z)
z[max_index] = 0
print("\nМассив после замены максимального элемента на 0:")
print(z)

Исходный массив z:
[0.57947581 0.39924351 0.49887912 0.44778753 0.13174736 0.67181578
 0.2210476  0.15833466 0.20416151 0.26580983]

Массив после замены максимального элемента на 0:
[0.57947581 0.39924351 0.49887912 0.44778753 0.13174736 0.
 0.2210476  0.15833466 0.20416151 0.26580983]


8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз

In [7]:
import numpy as np
z = np.ones(10)
i = np.random.randint(0, len(z), 20)
print("Исходный массив z:")
print(z)
print("\nМассив индексов i:")
print(i)
unique_i = np.unique(i)
z[unique_i] += 1
print("\nМассив z после добавления 1 к уникальным индексам из i:")
print(z)

Исходный массив z:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

Массив индексов i:
[3 7 4 5 3 5 8 2 1 4 9 9 4 6 0 2 5 8 3 2]

Массив z после добавления 1 к уникальным индексам из i:
[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]


9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [8]:
import numpy as np

z = np.array([1, 2, 3, 4, 5])

print("Исходный вектор z:")
print(z)
k = 3
step = k + 1
new_length = len(z) + (len(z) - 1) * k
new_z = np.zeros(new_length)
new_z[::step] = z
print("\nНовый вектор с тремя нулями между каждым значением:")
print(new_z)


Исходный вектор z:
[1 2 3 4 5]

Новый вектор с тремя нулями между каждым значением:
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


10. Найти ближайшее к заданному значению число в заданном массиве

In [10]:
import numpy as np
z = np.arange(100)
v = np.random.uniform(0, 100)
print("Массив z:")
print(z)
print(f"\nЗаданное значение v: {v}")
differences = np.abs(z - v)
closest_index = np.argmin(differences)
closest_value = z[closest_index]
print(f"\nБлижайшее значение: {closest_value} (индекс {closest_index})")

Массив z:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

Заданное значение v: 84.83085315493865

Ближайшее значение: 85 (индекс 85)


## Вопросы




**1**. Какой тип (dtype) будут иметь элементы массива?
``` python
np.array([1, 4, 2, 5, 3])
np.array([1., 4, 2, 5, 3])
np.array([1, 4, 2, 5, 3], dtype='float128')
np.array([1., 4, 2, 5, 3], dtype='complex128')
np.array([1, 4, 2, 5, 3], dtype ='float64')
np.array([1, 4, 2, 5, 3], dtype =int64)
np.array([1, 4, 2, 5, 3], dtype='bool')
np.array([1, 4, 2, 5, 3], dtype='str')
np.array([1, 4, 2, 5, '3'])
np.array([1, -4, 2, 0, 1j])
```

**2**. Что будет выведено в консоль и почему?
``` python
np.array([1, 4, 2, 5, 3], dtype='str')[1] + '1'
np.array([1, -4, 2, 0, 3], dtype='bool')[3] or np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, 3], dtype='bool')[3] and np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, True], dtype='int64')[-1]
np.array([1, -4, 2, 0, 1j], dtype='int64')[1]
np.array([1, -4, 2, 0, 1j], dtype='str')[-1]
np.array([1, 4, 2, 5, '3'])[-1] * 3
```

**3**. Каков результат операции?

``` python
np.ones((3, 5), dtype=float)
np.full((3, 5), 3.14)
np.linspace(0, 1, 5)
np.diag((1,3,5))
np.smile((1,3,5))
np.random.random((3, 3))
np.eye(3)
np.empty(3)
```



**4**. Дан двумерный массив X, что будет выведено в консоль?

``` python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])
```

``` python
X[0,0]
X[-1,-1]
X[0:1,-1]
X[0:2,-1]
X[0:2,0:2]
X[1,1:3]
X[1,:]
X[1,:]
X[:,:]
X[:]
X[::2,::2]
X[0:3:2,0:3:2]
X[::-1,::-1]
```

**5**. Дан двумерный массив grid, в чем различее между операциями?


``` python
grid = np.arange(16).reshape((4, 4))
```

``` python
np.split(grid, [2])
np.split(grid, [2], axis=1)
```


**6**. В чем различие между операциями?

``` python
    [1, 2, 3] + [3, 2, 1]
    np.array([1, 2, 3]) + np.array([3, 2, 1])
```

**7**. Как в CodeLab измерить время выполнения кода?

**8**. Дан массив X, каковы результаты операций?

```python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])

np.sum(M)
np.sum(M, axis=1)
np.sum(M, axis=0)
np.sum(M, axis=2)
np.sum(M, 1)
sum(M)
sum(M,1)
```

**9**. Дан массив X, что будет выведено в консоль?

```python
X = np.array([1,2,3,4])

X > 3
X < 3
X[X < 3]
X[X > 3]
X[X != 3]
```

**10**.  В чем преимущество массивов NumPy по сравнению с обычными списками.  Чем обусловлено это преимущество?